
##services:
#    faianca_site.example:
#        class: %faianca_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
   faianca.blog.admin.post:
      class: Faianca\SiteBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: faianca_blog, label: post }
      arguments: [null, Faianca\SiteBundle\Entity\Blog\Post, FaiancaSiteBundle:PostAdmin]
   
   faianca_blog.menu_builder:
        class: Faianca\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

   faianca_blog.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: faianca_blog.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu